package Midi.behavior;

/*Generated by MPS */


public class BinaryHelper {
  public static byte[] numRep32(int num) {
    int bitmask = 0b11111111;

    byte a = (byte) ((num >> 24) & bitmask);
    byte b = (byte) ((num >> 16) & bitmask);
    byte c = (byte) ((num >> 8) & bitmask);
    byte d = (byte) (num & bitmask);

    return new byte[]{a, b, c, d};
  }

  public static byte[] variableLengthQuantity(int num) {
    int more = 0b10000000;
    int done = 0b01111111;

    byte b = (byte) ((num >> 21) & done);
    byte c = (byte) ((num >> 14) & done);
    byte d = (byte) ((num >> 7) & done);
    byte e = (byte) (num & done);

    if (b > 0) {
      return new byte[]{(byte) (b | more), (byte) (c | more), (byte) (d | more), (byte) (e & done)};
    } else if (c > 0) {
      return new byte[]{(byte) (c | more), (byte) (d | more), (byte) (e & done)};
    } else if (d > 0) {
      return new byte[]{(byte) (d | more), (byte) (e & done)};
    } else {
      return new byte[]{(byte) (e & done)};
    }
  }
}
