package MetaMidi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_NoteName extends EnumerationDescriptorBase {

  public EnumerationDescriptor_NoteName() {
    super(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "NoteName", "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262082645");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_C_0 = new EnumerationDescriptor.MemberDescriptor("C", "C", 0x7c255ef757aa7e56L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262082646");
  private final EnumerationDescriptor.MemberDescriptor myMember_CSharp_0 = new EnumerationDescriptor.MemberDescriptor("CSharp", "C#", 0x7c255ef757ab858eL, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150030");
  private final EnumerationDescriptor.MemberDescriptor myMember_DFlat_0 = new EnumerationDescriptor.MemberDescriptor("DFlat", "D♭", 0x7c255ef757ab85b5L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150069");
  private final EnumerationDescriptor.MemberDescriptor myMember_D_0 = new EnumerationDescriptor.MemberDescriptor("D", "D", 0x7c255ef757ab862aL, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150186");
  private final EnumerationDescriptor.MemberDescriptor myMember_DSharp_0 = new EnumerationDescriptor.MemberDescriptor("DSharp", "D#", 0x7c255ef757ab866dL, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150253");
  private final EnumerationDescriptor.MemberDescriptor myMember_EFlat_0 = new EnumerationDescriptor.MemberDescriptor("EFlat", "E♭", 0x7c255ef757ab8692L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150290");
  private final EnumerationDescriptor.MemberDescriptor myMember_E_0 = new EnumerationDescriptor.MemberDescriptor("E", "E", 0x7c255ef757ab86b8L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150328");
  private final EnumerationDescriptor.MemberDescriptor myMember_F_0 = new EnumerationDescriptor.MemberDescriptor("F", "F", 0x7c255ef757ab86d5L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150357");
  private final EnumerationDescriptor.MemberDescriptor myMember_FSharp_0 = new EnumerationDescriptor.MemberDescriptor("FSharp", "F#", 0x7c255ef757ab86f3L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150387");
  private final EnumerationDescriptor.MemberDescriptor myMember_GFlat_0 = new EnumerationDescriptor.MemberDescriptor("GFlat", "G♭", 0x7c255ef757ab8726L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150438");
  private final EnumerationDescriptor.MemberDescriptor myMember_G_0 = new EnumerationDescriptor.MemberDescriptor("G", "G", 0x7c255ef757ab8764L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150500");
  private final EnumerationDescriptor.MemberDescriptor myMember_GSharp_0 = new EnumerationDescriptor.MemberDescriptor("GSharp", "G#", 0x7c255ef757ab8785L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150533");
  private final EnumerationDescriptor.MemberDescriptor myMember_AFlat_0 = new EnumerationDescriptor.MemberDescriptor("AFlat", "A♭", 0x7c255ef757ab87bbL, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150587");
  private final EnumerationDescriptor.MemberDescriptor myMember_A_0 = new EnumerationDescriptor.MemberDescriptor("A", "A", 0x7c255ef757ab87e8L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150632");
  private final EnumerationDescriptor.MemberDescriptor myMember_ASharp_0 = new EnumerationDescriptor.MemberDescriptor("ASharp", "A#", 0x7c255ef757ab880cL, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150668");
  private final EnumerationDescriptor.MemberDescriptor myMember_BFlat_0 = new EnumerationDescriptor.MemberDescriptor("BFlat", "B♭", 0x7c255ef757ab8831L, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150705");
  private final EnumerationDescriptor.MemberDescriptor myMember_B_0 = new EnumerationDescriptor.MemberDescriptor("B", "B", 0x7c255ef757ab886bL, "r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262150763");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, 0x7c255ef757aa7e56L, 0x7c255ef757ab858eL, 0x7c255ef757ab85b5L, 0x7c255ef757ab862aL, 0x7c255ef757ab866dL, 0x7c255ef757ab8692L, 0x7c255ef757ab86b8L, 0x7c255ef757ab86d5L, 0x7c255ef757ab86f3L, 0x7c255ef757ab8726L, 0x7c255ef757ab8764L, 0x7c255ef757ab8785L, 0x7c255ef757ab87bbL, 0x7c255ef757ab87e8L, 0x7c255ef757ab880cL, 0x7c255ef757ab8831L, 0x7c255ef757ab886bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_C_0, myMember_CSharp_0, myMember_DFlat_0, myMember_D_0, myMember_DSharp_0, myMember_EFlat_0, myMember_E_0, myMember_F_0, myMember_FSharp_0, myMember_GFlat_0, myMember_G_0, myMember_GSharp_0, myMember_AFlat_0, myMember_A_0, myMember_ASharp_0, myMember_BFlat_0, myMember_B_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "C":
        return myMember_C_0;
      case "CSharp":
        return myMember_CSharp_0;
      case "DFlat":
        return myMember_DFlat_0;
      case "D":
        return myMember_D_0;
      case "DSharp":
        return myMember_DSharp_0;
      case "EFlat":
        return myMember_EFlat_0;
      case "E":
        return myMember_E_0;
      case "F":
        return myMember_F_0;
      case "FSharp":
        return myMember_FSharp_0;
      case "GFlat":
        return myMember_GFlat_0;
      case "G":
        return myMember_G_0;
      case "GSharp":
        return myMember_GSharp_0;
      case "AFlat":
        return myMember_AFlat_0;
      case "A":
        return myMember_A_0;
      case "ASharp":
        return myMember_ASharp_0;
      case "BFlat":
        return myMember_BFlat_0;
      case "B":
        return myMember_B_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
