package MetaMidi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptArpeggio = createDescriptorForArpeggio();
  /*package*/ final ConceptDescriptor myConceptEventList = createDescriptorForEventList();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, "Midi");
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0x87d1018d30c44219L, 0x852f1bd942b093e8L, "MusicTheoryLang");
    deps.aggregatedLanguage(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, "Midi");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptArpeggio, myConceptEventList);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Arpeggio:
        return myConceptArpeggio;
      case LanguageConceptSwitch.EventList:
        return myConceptEventList;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForArpeggio() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MetaMidi", "Arpeggio", 0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757a97c04L);
    b.class_(false, false, false);
    // extends: Midi.structure.TrackEvent
    b.super_(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, 0x7c255ef7567ae92aL);
    b.origin("r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262016516");
    b.version(3);
    b.property("loops", 0x7c255ef757aa80f3L).type(PrimitiveTypeId.INTEGER).origin("8945660651262083315").done();
    b.property("pause", 0x7c255ef757aa8129L).type(PrimitiveTypeId.INTEGER).origin("8945660651262083369").done();
    b.aggregate("chord", 0x7c255ef757aa805eL).target(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757f95629L).optional(false).ordered(true).multiple(false).origin("8945660651262083166").done();
    b.alias("arpeggio");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEventList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MetaMidi", "EventList", 0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757ad7b8aL);
    b.class_(false, false, false);
    b.origin("r:a90fdff5-2f3c-4579-9b63-f5d2f00b9cd0(MetaMidi.structure)/8945660651262278538");
    b.version(3);
    b.aggregate("events", 0x7c255ef757ad7bc3L).target(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, 0x7c255ef7567ae92aL).optional(true).ordered(true).multiple(true).origin("8945660651262278595").done();
    return b.create();
  }
}
