package Midi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_KeyMajorMinor extends EnumerationDescriptorBase {

  public EnumerationDescriptor_KeyMajorMinor() {
    super(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, 0x7c255ef756ebb890L, "KeyMajorMinor", "r:b9dd644d-910d-4c92-935c-1cee59d546f7(Midi.structure)/8945660651249580176");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_major_0 = new EnumerationDescriptor.MemberDescriptor("major", "major", 0x7c255ef756ebb891L, "r:b9dd644d-910d-4c92-935c-1cee59d546f7(Midi.structure)/8945660651249580177");
  private final EnumerationDescriptor.MemberDescriptor myMember_minor_0 = new EnumerationDescriptor.MemberDescriptor("minor", "minor", 0x7c255ef756ebb8c1L, "r:b9dd644d-910d-4c92-935c-1cee59d546f7(Midi.structure)/8945660651249580225");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, 0x7c255ef756ebb890L, 0x7c255ef756ebb891L, 0x7c255ef756ebb8c1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_major_0, myMember_minor_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "major":
        return myMember_major_0;
      case "minor":
        return myMember_minor_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
