package MidiImporter.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.ide.actions.ModelNewActions_ActionGroup;

public class MidiImporter_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("MidiImporter");

  public MidiImporter_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters
    addAction(new ImportMidiFile_Action());
    // groups
    addGroup(new MidiFileGroup_ActionGroup(this));
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(MidiFileGroup_ActionGroup.ID, ModelNewActions_ActionGroup.ID, ModelNewActions_ActionGroup.LABEL_ID_newRoot);
  }
}
