package MetaMidi.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import java.util.Deque;
import jetbrains.mps.internal.collections.runtime.LinkedListSequence;
import java.util.LinkedList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class MajorChord__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7fc7L, "MetaMidi.structure.MajorChord");

  public static final SMethod<Iterable<SNode>> notes_id7K_nJtnFGsG = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("notes").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8945660651262363436L).languageId(0x8909a29a1d64fb03L, 0x3ba274977a154e85L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(notes_id7K_nJtnFGsG);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static Iterable<SNode> notes_id7K_nJtnFGsG(@NotNull SNode __thisNode__) {
    Deque<SNode> notes = LinkedListSequence.fromLinkedList(new LinkedList<SNode>());

    if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757aa7e56L, "C")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757aa7e56L, "C")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86b8L, "E")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8764L, "G")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab858eL, "CSharp")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab858eL, "CSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86d5L, "F")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8785L, "GSharp")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab85b5L, "DFlat")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab85b5L, "DFlat")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86d5L, "F")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab87bbL, "AFlat")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab862aL, "D")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab862aL, "D")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86f3L, "FSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab87e8L, "A")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab866dL, "DSharp")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab866dL, "DSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8764L, "G")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab880cL, "ASharp")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8692L, "EFlat")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8692L, "EFlat")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8764L, "G")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8831L, "BFlat")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86b8L, "E")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86b8L, "E")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8785L, "GSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab886bL, "B")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86d5L, "F")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86d5L, "F")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab87e8L, "A")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757aa7e56L, "C")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86f3L, "FSharp")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86f3L, "FSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab880cL, "ASharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab858eL, "CSharp")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8726L, "GFlat")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8726L, "GFlat")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8831L, "BFlat")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab85b5L, "DFlat")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8764L, "G")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8764L, "G")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab886bL, "B")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab862aL, "D")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8785L, "GSharp")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8785L, "GSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757aa7e56L, "C")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab866dL, "DSharp")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab87bbL, "AFlat")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab87bbL, "AFlat")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757aa7e56L, "C")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8692L, "EFlat")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab87e8L, "A")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab87e8L, "A")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab858eL, "CSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86b8L, "E")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab880cL, "ASharp")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab880cL, "ASharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab862aL, "D")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86d5L, "F")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8831L, "BFlat")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab8831L, "BFlat")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab862aL, "D")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86d5L, "F")));
    } else if (SPropertyOperations.getEnum(__thisNode__, PROPS.root$8$Bb) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab886bL, "B")) {
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab886bL, "B")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab866dL, "DSharp")));
      LinkedListSequence.fromLinkedListNew(notes).addElement(Note__BehaviorDescriptor.withName_id7K_nJtnFHM0.invoke(SNodeOperations.asSConcept(CONCEPTS.Note$Bc), SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7e55L, "MetaMidi.structure.NoteName"), 0x7c255ef757ab86f3L, "FSharp")));
    }

    return notes;
  }

  /*package*/ MajorChord__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Iterable<SNode>) notes_id7K_nJtnFGsG(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Note$Bc = MetaAdapterFactory.getConcept(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aec7e5L, "MetaMidi.structure.Note");
  }

  private static final class PROPS {
    /*package*/ static final SProperty root$8$Bb = MetaAdapterFactory.getProperty(0x3ba274977a154e85L, 0x8909a29a1d64fb03L, 0x7c255ef757aa7fc7L, 0x7c255ef757aaf596L, "root");
  }
}
