package Midi.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Timecode_Constraints extends BaseConstraintsDescriptor {
  public Timecode_Constraints() {
    super(CONCEPTS.Timecode$jg);
  }

  public static class Ticks_per_frame_Property extends BasePropertyConstraintsDescriptor {
    public Ticks_per_frame_Property(ConstraintsDescriptor container) {
      super(PROPS.ticks_per_frame$NgHQ, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e4bd7c6d-6c81-4354-9563-d855e9c2c4da(Midi.constraints)", "8945660651242038822"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 0 && propertyValue <= 0b1111111;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.ticks_per_frame$NgHQ, new Ticks_per_frame_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Timecode$jg = MetaAdapterFactory.getConcept(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, 0x7c255ef75678a573L, "Midi.structure.Timecode");
  }

  private static final class PROPS {
    /*package*/ static final SProperty ticks_per_frame$NgHQ = MetaAdapterFactory.getProperty(0x35a3fd90d0264551L, 0xaa863ed1bd51d7c6L, 0x7c255ef75678a573L, 0x7c255ef75678a59bL, "ticks_per_frame");
  }
}
